// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class NativeTransferJob {
  NativeTransferJob({
    required this.transferId,
    required this.endpoint,
    required this.localPath,
    required this.method,
    this.headers = const <String, String>{},
    this.expectedBytes,
    this.contentType,
  });

  String transferId;

  String endpoint;

  String localPath;

  String method;

  Map<String, String> headers;

  int? expectedBytes;

  String? contentType;

  List<Object?> _toList() {
    return <Object?>[
      transferId,
      endpoint,
      localPath,
      method,
      headers,
      expectedBytes,
      contentType,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeTransferJob decode(Object result) {
    result as List<Object?>;
    return NativeTransferJob(
      transferId: result[0]! as String,
      endpoint: result[1]! as String,
      localPath: result[2]! as String,
      method: result[3]! as String,
      headers: (result[4]! as Map<Object?, Object?>).cast<String, String>(),
      expectedBytes: result[5] as int?,
      contentType: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeTransferJob || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(transferId, other.transferId) && _deepEquals(endpoint, other.endpoint) && _deepEquals(localPath, other.localPath) && _deepEquals(method, other.method) && _deepEquals(headers, other.headers) && _deepEquals(expectedBytes, other.expectedBytes) && _deepEquals(contentType, other.contentType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeTransferProgressEvent {
  NativeTransferProgressEvent({
    required this.transferId,
    required this.bytesTransferred,
    required this.totalBytes,
    required this.isUpload,
  });

  String transferId;

  int bytesTransferred;

  int totalBytes;

  bool isUpload;

  List<Object?> _toList() {
    return <Object?>[
      transferId,
      bytesTransferred,
      totalBytes,
      isUpload,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeTransferProgressEvent decode(Object result) {
    result as List<Object?>;
    return NativeTransferProgressEvent(
      transferId: result[0]! as String,
      bytesTransferred: result[1]! as int,
      totalBytes: result[2]! as int,
      isUpload: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeTransferProgressEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(transferId, other.transferId) && _deepEquals(bytesTransferred, other.bytesTransferred) && _deepEquals(totalBytes, other.totalBytes) && _deepEquals(isUpload, other.isUpload);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeTransferSnapshot {
  NativeTransferSnapshot({
    required this.transferId,
    required this.state,
    required this.bytesTransferred,
    required this.totalBytes,
    this.failureMessage,
  });

  String transferId;

  String state;

  int bytesTransferred;

  int totalBytes;

  String? failureMessage;

  List<Object?> _toList() {
    return <Object?>[
      transferId,
      state,
      bytesTransferred,
      totalBytes,
      failureMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeTransferSnapshot decode(Object result) {
    result as List<Object?>;
    return NativeTransferSnapshot(
      transferId: result[0]! as String,
      state: result[1]! as String,
      bytesTransferred: result[2]! as int,
      totalBytes: result[3]! as int,
      failureMessage: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeTransferSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(transferId, other.transferId) && _deepEquals(state, other.state) && _deepEquals(bytesTransferred, other.bytesTransferred) && _deepEquals(totalBytes, other.totalBytes) && _deepEquals(failureMessage, other.failureMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeCommandResult {
  NativeCommandResult({
    required this.accepted,
    this.message,
  });

  bool accepted;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      accepted,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCommandResult decode(Object result) {
    result as List<Object?>;
    return NativeCommandResult(
      accepted: result[0]! as bool,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCommandResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accepted, other.accepted) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Request to save a received file into the platform's native media store:
/// `PHPhotoLibrary` / Files-app share sheet on iOS,
/// `MediaStore.Downloads` / `MediaStore.Images` / `MediaStore.Video` on Android.
class SaveFileRequest {
  SaveFileRequest({
    required this.localPath,
    required this.mimeType,
    required this.displayName,
  });

  String localPath;

  String mimeType;

  String displayName;

  List<Object?> _toList() {
    return <Object?>[
      localPath,
      mimeType,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static SaveFileRequest decode(Object result) {
    result as List<Object?>;
    return SaveFileRequest(
      localPath: result[0]! as String,
      mimeType: result[1]! as String,
      displayName: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SaveFileRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(localPath, other.localPath) && _deepEquals(mimeType, other.mimeType) && _deepEquals(displayName, other.displayName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Outcome of a native save operation.
///
/// `savedUri` is filled by Android (the MediaStore content:// URI) so the
/// caller can later surface an "Open" action; iOS does not return a usable
/// URI (Photos saves are identifier-based), so this stays null.
class SaveFileResult {
  SaveFileResult({
    required this.success,
    this.savedUri,
    this.message,
  });

  bool success;

  String? savedUri;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      success,
      savedUri,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static SaveFileResult decode(Object result) {
    result as List<Object?>;
    return SaveFileResult(
      success: result[0]! as bool,
      savedUri: result[1] as String?,
      message: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SaveFileResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(savedUri, other.savedUri) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A single file picked by the platform-native document picker.
///
/// `localPath` is always a readable path inside the app sandbox — the native
/// impl copies the picked file locally before returning, so the Dart side can
/// open it without worrying about security-scoped resources (iOS) or content
/// URI lifetime (Android).
class PickedFile {
  PickedFile({
    required this.id,
    required this.name,
    required this.localPath,
    required this.mimeType,
    required this.byteCount,
    this.sourceIdentifier,
  });

  String id;

  String name;

  String localPath;

  String mimeType;

  int byteCount;

  String? sourceIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      localPath,
      mimeType,
      byteCount,
      sourceIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static PickedFile decode(Object result) {
    result as List<Object?>;
    return PickedFile(
      id: result[0]! as String,
      name: result[1]! as String,
      localPath: result[2]! as String,
      mimeType: result[3]! as String,
      byteCount: result[4]! as int,
      sourceIdentifier: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickedFile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(localPath, other.localPath) && _deepEquals(mimeType, other.mimeType) && _deepEquals(byteCount, other.byteCount) && _deepEquals(sourceIdentifier, other.sourceIdentifier);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PickFilesResult {
  PickFilesResult({
    required this.files,
    this.cancelled = false,
    this.message,
  });

  List<PickedFile?> files;

  bool cancelled;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      files,
      cancelled,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static PickFilesResult decode(Object result) {
    result as List<Object?>;
    return PickFilesResult(
      files: (result[0]! as List<Object?>).cast<PickedFile?>(),
      cancelled: result[1]! as bool,
      message: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickFilesResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(files, other.files) && _deepEquals(cancelled, other.cancelled) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeTransferJob) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeTransferProgressEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativeTransferSnapshot) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCommandResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is SaveFileRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is SaveFileResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PickedFile) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PickFilesResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeTransferJob.decode(readValue(buffer)!);
      case 130:
        return NativeTransferProgressEvent.decode(readValue(buffer)!);
      case 131:
        return NativeTransferSnapshot.decode(readValue(buffer)!);
      case 132:
        return NativeCommandResult.decode(readValue(buffer)!);
      case 133:
        return SaveFileRequest.decode(readValue(buffer)!);
      case 134:
        return SaveFileResult.decode(readValue(buffer)!);
      case 135:
        return PickedFile.decode(readValue(buffer)!);
      case 136:
        return PickFilesResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeTransferHostApi {
  /// Constructor for [NativeTransferHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeTransferHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeCommandResult> startTransfer(NativeTransferJob job) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.startTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[job]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCommandResult;
  }

  Future<NativeCommandResult> pauseTransfer(String transferId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.pauseTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[transferId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCommandResult;
  }

  Future<NativeCommandResult> resumeTransfer(String transferId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.resumeTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[transferId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCommandResult;
  }

  Future<NativeCommandResult> cancelTransfer(String transferId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.cancelTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[transferId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCommandResult;
  }

  Future<List<NativeTransferSnapshot?>> queryActiveTransfers() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.queryActiveTransfers$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeTransferSnapshot?>();
  }
}

/// Thin host API specifically for native media save — Bonus E.
/// Kept separate from `NativeTransferHostApi` so the two bonus tracks
/// (background transfer + native save) can ship independently.
class NativeMediaSaverHostApi {
  /// Constructor for [NativeMediaSaverHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeMediaSaverHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<SaveFileResult> saveFileToGallery(SaveFileRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeMediaSaverHostApi.saveFileToGallery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as SaveFileResult;
  }
}

/// Native document-picker host API — Bonus D.
///   Android: `ACTION_OPEN_DOCUMENT`
///   iOS:     `UIDocumentPickerViewController`
///
/// Keeps a typed contract at the Pigeon boundary so neither side hand-rolls a
/// method-channel string. Returns cancelled=true when the user dismisses
/// the picker without choosing anything; returns an empty files list only if
/// the OS reported success with zero URIs (rare).
class NativeFilePickerHostApi {
  /// Constructor for [NativeFilePickerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeFilePickerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<PickFilesResult> pickFiles(bool allowMultiple) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.neo_sapien.NativeFilePickerHostApi.pickFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[allowMultiple]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PickFilesResult;
  }
}

abstract class NativeTransferFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(NativeTransferProgressEvent event);

  void onStateChanged(NativeTransferSnapshot snapshot);

  static void setUp(NativeTransferFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeTransferProgressEvent arg_event = args[0]! as NativeTransferProgressEvent;
          try {
            api.onProgress(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeTransferSnapshot arg_snapshot = args[0]! as NativeTransferSnapshot;
          try {
            api.onStateChanged(arg_snapshot);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
