// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsNativeTransferBridge(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashNativeTransferBridge(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsNativeTransferBridge(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsNativeTransferBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsNativeTransferBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsNativeTransferBridge(lhsKey, rhsKey) {
          if deepEqualsNativeTransferBridge(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsNativeTransferBridge(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashNativeTransferBridge(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashNativeTransferBridge(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashNativeTransferBridge(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashNativeTransferBridge(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashNativeTransferBridge(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashNativeTransferBridge(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeTransferJob: Hashable {
  var transferId: String
  var endpoint: String
  var localPath: String
  var method: String
  var headers: [String: String]
  var expectedBytes: Int64? = nil
  var contentType: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTransferJob? {
    let transferId = pigeonVar_list[0] as! String
    let endpoint = pigeonVar_list[1] as! String
    let localPath = pigeonVar_list[2] as! String
    let method = pigeonVar_list[3] as! String
    let headers = pigeonVar_list[4] as! [String: String]
    let expectedBytes: Int64? = nilOrValue(pigeonVar_list[5])
    let contentType: String? = nilOrValue(pigeonVar_list[6])

    return NativeTransferJob(
      transferId: transferId,
      endpoint: endpoint,
      localPath: localPath,
      method: method,
      headers: headers,
      expectedBytes: expectedBytes,
      contentType: contentType
    )
  }
  func toList() -> [Any?] {
    return [
      transferId,
      endpoint,
      localPath,
      method,
      headers,
      expectedBytes,
      contentType,
    ]
  }
  static func == (lhs: NativeTransferJob, rhs: NativeTransferJob) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.transferId, rhs.transferId) && deepEqualsNativeTransferBridge(lhs.endpoint, rhs.endpoint) && deepEqualsNativeTransferBridge(lhs.localPath, rhs.localPath) && deepEqualsNativeTransferBridge(lhs.method, rhs.method) && deepEqualsNativeTransferBridge(lhs.headers, rhs.headers) && deepEqualsNativeTransferBridge(lhs.expectedBytes, rhs.expectedBytes) && deepEqualsNativeTransferBridge(lhs.contentType, rhs.contentType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeTransferJob")
    deepHashNativeTransferBridge(value: transferId, hasher: &hasher)
    deepHashNativeTransferBridge(value: endpoint, hasher: &hasher)
    deepHashNativeTransferBridge(value: localPath, hasher: &hasher)
    deepHashNativeTransferBridge(value: method, hasher: &hasher)
    deepHashNativeTransferBridge(value: headers, hasher: &hasher)
    deepHashNativeTransferBridge(value: expectedBytes, hasher: &hasher)
    deepHashNativeTransferBridge(value: contentType, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeTransferProgressEvent: Hashable {
  var transferId: String
  var bytesTransferred: Int64
  var totalBytes: Int64
  var isUpload: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTransferProgressEvent? {
    let transferId = pigeonVar_list[0] as! String
    let bytesTransferred = pigeonVar_list[1] as! Int64
    let totalBytes = pigeonVar_list[2] as! Int64
    let isUpload = pigeonVar_list[3] as! Bool

    return NativeTransferProgressEvent(
      transferId: transferId,
      bytesTransferred: bytesTransferred,
      totalBytes: totalBytes,
      isUpload: isUpload
    )
  }
  func toList() -> [Any?] {
    return [
      transferId,
      bytesTransferred,
      totalBytes,
      isUpload,
    ]
  }
  static func == (lhs: NativeTransferProgressEvent, rhs: NativeTransferProgressEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.transferId, rhs.transferId) && deepEqualsNativeTransferBridge(lhs.bytesTransferred, rhs.bytesTransferred) && deepEqualsNativeTransferBridge(lhs.totalBytes, rhs.totalBytes) && deepEqualsNativeTransferBridge(lhs.isUpload, rhs.isUpload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeTransferProgressEvent")
    deepHashNativeTransferBridge(value: transferId, hasher: &hasher)
    deepHashNativeTransferBridge(value: bytesTransferred, hasher: &hasher)
    deepHashNativeTransferBridge(value: totalBytes, hasher: &hasher)
    deepHashNativeTransferBridge(value: isUpload, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeTransferSnapshot: Hashable {
  var transferId: String
  var state: String
  var bytesTransferred: Int64
  var totalBytes: Int64
  var failureMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTransferSnapshot? {
    let transferId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! String
    let bytesTransferred = pigeonVar_list[2] as! Int64
    let totalBytes = pigeonVar_list[3] as! Int64
    let failureMessage: String? = nilOrValue(pigeonVar_list[4])

    return NativeTransferSnapshot(
      transferId: transferId,
      state: state,
      bytesTransferred: bytesTransferred,
      totalBytes: totalBytes,
      failureMessage: failureMessage
    )
  }
  func toList() -> [Any?] {
    return [
      transferId,
      state,
      bytesTransferred,
      totalBytes,
      failureMessage,
    ]
  }
  static func == (lhs: NativeTransferSnapshot, rhs: NativeTransferSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.transferId, rhs.transferId) && deepEqualsNativeTransferBridge(lhs.state, rhs.state) && deepEqualsNativeTransferBridge(lhs.bytesTransferred, rhs.bytesTransferred) && deepEqualsNativeTransferBridge(lhs.totalBytes, rhs.totalBytes) && deepEqualsNativeTransferBridge(lhs.failureMessage, rhs.failureMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeTransferSnapshot")
    deepHashNativeTransferBridge(value: transferId, hasher: &hasher)
    deepHashNativeTransferBridge(value: state, hasher: &hasher)
    deepHashNativeTransferBridge(value: bytesTransferred, hasher: &hasher)
    deepHashNativeTransferBridge(value: totalBytes, hasher: &hasher)
    deepHashNativeTransferBridge(value: failureMessage, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCommandResult: Hashable {
  var accepted: Bool
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCommandResult? {
    let accepted = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])

    return NativeCommandResult(
      accepted: accepted,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      accepted,
      message,
    ]
  }
  static func == (lhs: NativeCommandResult, rhs: NativeCommandResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.accepted, rhs.accepted) && deepEqualsNativeTransferBridge(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCommandResult")
    deepHashNativeTransferBridge(value: accepted, hasher: &hasher)
    deepHashNativeTransferBridge(value: message, hasher: &hasher)
  }
}

/// Request to save a received file into the platform's native media store:
/// `PHPhotoLibrary` / Files-app share sheet on iOS,
/// `MediaStore.Downloads` / `MediaStore.Images` / `MediaStore.Video` on Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SaveFileRequest: Hashable {
  var localPath: String
  var mimeType: String
  var displayName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SaveFileRequest? {
    let localPath = pigeonVar_list[0] as! String
    let mimeType = pigeonVar_list[1] as! String
    let displayName = pigeonVar_list[2] as! String

    return SaveFileRequest(
      localPath: localPath,
      mimeType: mimeType,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      localPath,
      mimeType,
      displayName,
    ]
  }
  static func == (lhs: SaveFileRequest, rhs: SaveFileRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.localPath, rhs.localPath) && deepEqualsNativeTransferBridge(lhs.mimeType, rhs.mimeType) && deepEqualsNativeTransferBridge(lhs.displayName, rhs.displayName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SaveFileRequest")
    deepHashNativeTransferBridge(value: localPath, hasher: &hasher)
    deepHashNativeTransferBridge(value: mimeType, hasher: &hasher)
    deepHashNativeTransferBridge(value: displayName, hasher: &hasher)
  }
}

/// Outcome of a native save operation.
///
/// `savedUri` is filled by Android (the MediaStore content:// URI) so the
/// caller can later surface an "Open" action; iOS does not return a usable
/// URI (Photos saves are identifier-based), so this stays null.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SaveFileResult: Hashable {
  var success: Bool
  var savedUri: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SaveFileResult? {
    let success = pigeonVar_list[0] as! Bool
    let savedUri: String? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])

    return SaveFileResult(
      success: success,
      savedUri: savedUri,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      savedUri,
      message,
    ]
  }
  static func == (lhs: SaveFileResult, rhs: SaveFileResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.success, rhs.success) && deepEqualsNativeTransferBridge(lhs.savedUri, rhs.savedUri) && deepEqualsNativeTransferBridge(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SaveFileResult")
    deepHashNativeTransferBridge(value: success, hasher: &hasher)
    deepHashNativeTransferBridge(value: savedUri, hasher: &hasher)
    deepHashNativeTransferBridge(value: message, hasher: &hasher)
  }
}

/// A single file picked by the platform-native document picker.
///
/// `localPath` is always a readable path inside the app sandbox — the native
/// impl copies the picked file locally before returning, so the Dart side can
/// open it without worrying about security-scoped resources (iOS) or content
/// URI lifetime (Android).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PickedFile: Hashable {
  var id: String
  var name: String
  var localPath: String
  var mimeType: String
  var byteCount: Int64
  var sourceIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickedFile? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let localPath = pigeonVar_list[2] as! String
    let mimeType = pigeonVar_list[3] as! String
    let byteCount = pigeonVar_list[4] as! Int64
    let sourceIdentifier: String? = nilOrValue(pigeonVar_list[5])

    return PickedFile(
      id: id,
      name: name,
      localPath: localPath,
      mimeType: mimeType,
      byteCount: byteCount,
      sourceIdentifier: sourceIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      localPath,
      mimeType,
      byteCount,
      sourceIdentifier,
    ]
  }
  static func == (lhs: PickedFile, rhs: PickedFile) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.id, rhs.id) && deepEqualsNativeTransferBridge(lhs.name, rhs.name) && deepEqualsNativeTransferBridge(lhs.localPath, rhs.localPath) && deepEqualsNativeTransferBridge(lhs.mimeType, rhs.mimeType) && deepEqualsNativeTransferBridge(lhs.byteCount, rhs.byteCount) && deepEqualsNativeTransferBridge(lhs.sourceIdentifier, rhs.sourceIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PickedFile")
    deepHashNativeTransferBridge(value: id, hasher: &hasher)
    deepHashNativeTransferBridge(value: name, hasher: &hasher)
    deepHashNativeTransferBridge(value: localPath, hasher: &hasher)
    deepHashNativeTransferBridge(value: mimeType, hasher: &hasher)
    deepHashNativeTransferBridge(value: byteCount, hasher: &hasher)
    deepHashNativeTransferBridge(value: sourceIdentifier, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PickFilesResult: Hashable {
  var files: [PickedFile?]
  var cancelled: Bool
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickFilesResult? {
    let files = pigeonVar_list[0] as! [PickedFile?]
    let cancelled = pigeonVar_list[1] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[2])

    return PickFilesResult(
      files: files,
      cancelled: cancelled,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      files,
      cancelled,
      message,
    ]
  }
  static func == (lhs: PickFilesResult, rhs: PickFilesResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNativeTransferBridge(lhs.files, rhs.files) && deepEqualsNativeTransferBridge(lhs.cancelled, rhs.cancelled) && deepEqualsNativeTransferBridge(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PickFilesResult")
    deepHashNativeTransferBridge(value: files, hasher: &hasher)
    deepHashNativeTransferBridge(value: cancelled, hasher: &hasher)
    deepHashNativeTransferBridge(value: message, hasher: &hasher)
  }
}

private class NativeTransferBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeTransferJob.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeTransferProgressEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeTransferSnapshot.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeCommandResult.fromList(self.readValue() as! [Any?])
    case 133:
      return SaveFileRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return SaveFileResult.fromList(self.readValue() as! [Any?])
    case 135:
      return PickedFile.fromList(self.readValue() as! [Any?])
    case 136:
      return PickFilesResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeTransferBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeTransferJob {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeTransferProgressEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeTransferSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCommandResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? SaveFileRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SaveFileResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PickedFile {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PickFilesResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeTransferBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeTransferBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeTransferBridgePigeonCodecWriter(data: data)
  }
}

class NativeTransferBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeTransferBridgePigeonCodec(readerWriter: NativeTransferBridgePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeTransferHostApi {
  func startTransfer(job: NativeTransferJob) throws -> NativeCommandResult
  func pauseTransfer(transferId: String) throws -> NativeCommandResult
  func resumeTransfer(transferId: String) throws -> NativeCommandResult
  func cancelTransfer(transferId: String) throws -> NativeCommandResult
  func queryActiveTransfers() throws -> [NativeTransferSnapshot?]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeTransferHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeTransferBridgePigeonCodec.shared }
  /// Sets up an instance of `NativeTransferHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeTransferHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.startTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobArg = args[0] as! NativeTransferJob
        do {
          let result = try api.startTransfer(job: jobArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startTransferChannel.setMessageHandler(nil)
    }
    let pauseTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.pauseTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transferIdArg = args[0] as! String
        do {
          let result = try api.pauseTransfer(transferId: transferIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseTransferChannel.setMessageHandler(nil)
    }
    let resumeTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.resumeTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transferIdArg = args[0] as! String
        do {
          let result = try api.resumeTransfer(transferId: transferIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeTransferChannel.setMessageHandler(nil)
    }
    let cancelTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.cancelTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transferIdArg = args[0] as! String
        do {
          let result = try api.cancelTransfer(transferId: transferIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelTransferChannel.setMessageHandler(nil)
    }
    let queryActiveTransfersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.queryActiveTransfers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryActiveTransfersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.queryActiveTransfers()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queryActiveTransfersChannel.setMessageHandler(nil)
    }
  }
}
/// Thin host API specifically for native media save — Bonus E.
/// Kept separate from `NativeTransferHostApi` so the two bonus tracks
/// (background transfer + native save) can ship independently.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeMediaSaverHostApi {
  func saveFileToGallery(request: SaveFileRequest, completion: @escaping (Result<SaveFileResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeMediaSaverHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeTransferBridgePigeonCodec.shared }
  /// Sets up an instance of `NativeMediaSaverHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeMediaSaverHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let saveFileToGalleryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeMediaSaverHostApi.saveFileToGallery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveFileToGalleryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveFileRequest
        api.saveFileToGallery(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveFileToGalleryChannel.setMessageHandler(nil)
    }
  }
}
/// Native document-picker host API — Bonus D.
///   Android: `ACTION_OPEN_DOCUMENT`
///   iOS:     `UIDocumentPickerViewController`
///
/// Keeps a typed contract at the Pigeon boundary so neither side hand-rolls a
/// method-channel string. Returns cancelled=true when the user dismisses
/// the picker without choosing anything; returns an empty files list only if
/// the OS reported success with zero URIs (rare).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeFilePickerHostApi {
  func pickFiles(allowMultiple: Bool, completion: @escaping (Result<PickFilesResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeFilePickerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeTransferBridgePigeonCodec.shared }
  /// Sets up an instance of `NativeFilePickerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeFilePickerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let pickFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neo_sapien.NativeFilePickerHostApi.pickFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickFilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let allowMultipleArg = args[0] as! Bool
        api.pickFiles(allowMultiple: allowMultipleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickFilesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeTransferFlutterApiProtocol {
  func onProgress(event eventArg: NativeTransferProgressEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStateChanged(snapshot snapshotArg: NativeTransferSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NativeTransferFlutterApi: NativeTransferFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeTransferBridgePigeonCodec {
    return NativeTransferBridgePigeonCodec.shared
  }
  func onProgress(event eventArg: NativeTransferProgressEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateChanged(snapshot snapshotArg: NativeTransferSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([snapshotArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
