// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.neosapien.assignment.neo_sapien

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeTransferBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeTransferJob (
  val transferId: String,
  val endpoint: String,
  val localPath: String,
  val method: String,
  val headers: Map<String, String>,
  val expectedBytes: Long? = null,
  val contentType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeTransferJob {
      val transferId = pigeonVar_list[0] as String
      val endpoint = pigeonVar_list[1] as String
      val localPath = pigeonVar_list[2] as String
      val method = pigeonVar_list[3] as String
      val headers = pigeonVar_list[4] as Map<String, String>
      val expectedBytes = pigeonVar_list[5] as Long?
      val contentType = pigeonVar_list[6] as String?
      return NativeTransferJob(transferId, endpoint, localPath, method, headers, expectedBytes, contentType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transferId,
      endpoint,
      localPath,
      method,
      headers,
      expectedBytes,
      contentType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeTransferJob
    return NativeTransferBridgePigeonUtils.deepEquals(this.transferId, other.transferId) && NativeTransferBridgePigeonUtils.deepEquals(this.endpoint, other.endpoint) && NativeTransferBridgePigeonUtils.deepEquals(this.localPath, other.localPath) && NativeTransferBridgePigeonUtils.deepEquals(this.method, other.method) && NativeTransferBridgePigeonUtils.deepEquals(this.headers, other.headers) && NativeTransferBridgePigeonUtils.deepEquals(this.expectedBytes, other.expectedBytes) && NativeTransferBridgePigeonUtils.deepEquals(this.contentType, other.contentType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.transferId)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.endpoint)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.localPath)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.method)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.headers)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.expectedBytes)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.contentType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeTransferProgressEvent (
  val transferId: String,
  val bytesTransferred: Long,
  val totalBytes: Long,
  val isUpload: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeTransferProgressEvent {
      val transferId = pigeonVar_list[0] as String
      val bytesTransferred = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      val isUpload = pigeonVar_list[3] as Boolean
      return NativeTransferProgressEvent(transferId, bytesTransferred, totalBytes, isUpload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transferId,
      bytesTransferred,
      totalBytes,
      isUpload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeTransferProgressEvent
    return NativeTransferBridgePigeonUtils.deepEquals(this.transferId, other.transferId) && NativeTransferBridgePigeonUtils.deepEquals(this.bytesTransferred, other.bytesTransferred) && NativeTransferBridgePigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && NativeTransferBridgePigeonUtils.deepEquals(this.isUpload, other.isUpload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.transferId)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.bytesTransferred)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.isUpload)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeTransferSnapshot (
  val transferId: String,
  val state: String,
  val bytesTransferred: Long,
  val totalBytes: Long,
  val failureMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeTransferSnapshot {
      val transferId = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as String
      val bytesTransferred = pigeonVar_list[2] as Long
      val totalBytes = pigeonVar_list[3] as Long
      val failureMessage = pigeonVar_list[4] as String?
      return NativeTransferSnapshot(transferId, state, bytesTransferred, totalBytes, failureMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      transferId,
      state,
      bytesTransferred,
      totalBytes,
      failureMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeTransferSnapshot
    return NativeTransferBridgePigeonUtils.deepEquals(this.transferId, other.transferId) && NativeTransferBridgePigeonUtils.deepEquals(this.state, other.state) && NativeTransferBridgePigeonUtils.deepEquals(this.bytesTransferred, other.bytesTransferred) && NativeTransferBridgePigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && NativeTransferBridgePigeonUtils.deepEquals(this.failureMessage, other.failureMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.transferId)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.state)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.bytesTransferred)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.failureMessage)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCommandResult (
  val accepted: Boolean,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCommandResult {
      val accepted = pigeonVar_list[0] as Boolean
      val message = pigeonVar_list[1] as String?
      return NativeCommandResult(accepted, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accepted,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCommandResult
    return NativeTransferBridgePigeonUtils.deepEquals(this.accepted, other.accepted) && NativeTransferBridgePigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.accepted)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.message)
    return result
  }
}

/**
 * Request to save a received file into the platform's native media store:
 * `PHPhotoLibrary` / Files-app share sheet on iOS,
 * `MediaStore.Downloads` / `MediaStore.Images` / `MediaStore.Video` on Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SaveFileRequest (
  val localPath: String,
  val mimeType: String,
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SaveFileRequest {
      val localPath = pigeonVar_list[0] as String
      val mimeType = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String
      return SaveFileRequest(localPath, mimeType, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      localPath,
      mimeType,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SaveFileRequest
    return NativeTransferBridgePigeonUtils.deepEquals(this.localPath, other.localPath) && NativeTransferBridgePigeonUtils.deepEquals(this.mimeType, other.mimeType) && NativeTransferBridgePigeonUtils.deepEquals(this.displayName, other.displayName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.localPath)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.mimeType)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.displayName)
    return result
  }
}

/**
 * Outcome of a native save operation.
 *
 * `savedUri` is filled by Android (the MediaStore content:// URI) so the
 * caller can later surface an "Open" action; iOS does not return a usable
 * URI (Photos saves are identifier-based), so this stays null.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SaveFileResult (
  val success: Boolean,
  val savedUri: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SaveFileResult {
      val success = pigeonVar_list[0] as Boolean
      val savedUri = pigeonVar_list[1] as String?
      val message = pigeonVar_list[2] as String?
      return SaveFileResult(success, savedUri, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      savedUri,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SaveFileResult
    return NativeTransferBridgePigeonUtils.deepEquals(this.success, other.success) && NativeTransferBridgePigeonUtils.deepEquals(this.savedUri, other.savedUri) && NativeTransferBridgePigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.success)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.savedUri)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.message)
    return result
  }
}

/**
 * A single file picked by the platform-native document picker.
 *
 * `localPath` is always a readable path inside the app sandbox — the native
 * impl copies the picked file locally before returning, so the Dart side can
 * open it without worrying about security-scoped resources (iOS) or content
 * URI lifetime (Android).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PickedFile (
  val id: String,
  val name: String,
  val localPath: String,
  val mimeType: String,
  val byteCount: Long,
  val sourceIdentifier: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickedFile {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val localPath = pigeonVar_list[2] as String
      val mimeType = pigeonVar_list[3] as String
      val byteCount = pigeonVar_list[4] as Long
      val sourceIdentifier = pigeonVar_list[5] as String?
      return PickedFile(id, name, localPath, mimeType, byteCount, sourceIdentifier)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      localPath,
      mimeType,
      byteCount,
      sourceIdentifier,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PickedFile
    return NativeTransferBridgePigeonUtils.deepEquals(this.id, other.id) && NativeTransferBridgePigeonUtils.deepEquals(this.name, other.name) && NativeTransferBridgePigeonUtils.deepEquals(this.localPath, other.localPath) && NativeTransferBridgePigeonUtils.deepEquals(this.mimeType, other.mimeType) && NativeTransferBridgePigeonUtils.deepEquals(this.byteCount, other.byteCount) && NativeTransferBridgePigeonUtils.deepEquals(this.sourceIdentifier, other.sourceIdentifier)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.name)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.localPath)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.mimeType)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.byteCount)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.sourceIdentifier)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PickFilesResult (
  val files: List<PickedFile?>,
  val cancelled: Boolean,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickFilesResult {
      val files = pigeonVar_list[0] as List<PickedFile?>
      val cancelled = pigeonVar_list[1] as Boolean
      val message = pigeonVar_list[2] as String?
      return PickFilesResult(files, cancelled, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      files,
      cancelled,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PickFilesResult
    return NativeTransferBridgePigeonUtils.deepEquals(this.files, other.files) && NativeTransferBridgePigeonUtils.deepEquals(this.cancelled, other.cancelled) && NativeTransferBridgePigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.files)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.cancelled)
    result = 31 * result + NativeTransferBridgePigeonUtils.deepHash(this.message)
    return result
  }
}
private open class NativeTransferBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeTransferJob.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeTransferProgressEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeTransferSnapshot.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCommandResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SaveFileRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SaveFileResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickedFile.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickFilesResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeTransferJob -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeTransferProgressEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeTransferSnapshot -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeCommandResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SaveFileRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SaveFileResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PickedFile -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PickFilesResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeTransferHostApi {
  fun startTransfer(job: NativeTransferJob): NativeCommandResult
  fun pauseTransfer(transferId: String): NativeCommandResult
  fun resumeTransfer(transferId: String): NativeCommandResult
  fun cancelTransfer(transferId: String): NativeCommandResult
  fun queryActiveTransfers(): List<NativeTransferSnapshot?>

  companion object {
    /** The codec used by NativeTransferHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeTransferBridgePigeonCodec()
    }
    /** Sets up an instance of `NativeTransferHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeTransferHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.startTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobArg = args[0] as NativeTransferJob
            val wrapped: List<Any?> = try {
              listOf(api.startTransfer(jobArg))
            } catch (exception: Throwable) {
              NativeTransferBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.pauseTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val transferIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.pauseTransfer(transferIdArg))
            } catch (exception: Throwable) {
              NativeTransferBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.resumeTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val transferIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.resumeTransfer(transferIdArg))
            } catch (exception: Throwable) {
              NativeTransferBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.cancelTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val transferIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.cancelTransfer(transferIdArg))
            } catch (exception: Throwable) {
              NativeTransferBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeTransferHostApi.queryActiveTransfers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.queryActiveTransfers())
            } catch (exception: Throwable) {
              NativeTransferBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Thin host API specifically for native media save — Bonus E.
 * Kept separate from `NativeTransferHostApi` so the two bonus tracks
 * (background transfer + native save) can ship independently.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeMediaSaverHostApi {
  fun saveFileToGallery(request: SaveFileRequest, callback: (Result<SaveFileResult>) -> Unit)

  companion object {
    /** The codec used by NativeMediaSaverHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeTransferBridgePigeonCodec()
    }
    /** Sets up an instance of `NativeMediaSaverHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeMediaSaverHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeMediaSaverHostApi.saveFileToGallery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SaveFileRequest
            api.saveFileToGallery(requestArg) { result: Result<SaveFileResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeTransferBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeTransferBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native document-picker host API — Bonus D.
 *   Android: `ACTION_OPEN_DOCUMENT`
 *   iOS:     `UIDocumentPickerViewController`
 *
 * Keeps a typed contract at the Pigeon boundary so neither side hand-rolls a
 * method-channel string. Returns cancelled=true when the user dismisses
 * the picker without choosing anything; returns an empty files list only if
 * the OS reported success with zero URIs (rare).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeFilePickerHostApi {
  fun pickFiles(allowMultiple: Boolean, callback: (Result<PickFilesResult>) -> Unit)

  companion object {
    /** The codec used by NativeFilePickerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeTransferBridgePigeonCodec()
    }
    /** Sets up an instance of `NativeFilePickerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeFilePickerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neo_sapien.NativeFilePickerHostApi.pickFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val allowMultipleArg = args[0] as Boolean
            api.pickFiles(allowMultipleArg) { result: Result<PickFilesResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeTransferBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeTransferBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NativeTransferFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NativeTransferFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeTransferBridgePigeonCodec()
    }
  }
  fun onProgress(eventArg: NativeTransferProgressEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeTransferBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStateChanged(snapshotArg: NativeTransferSnapshot, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.neo_sapien.NativeTransferFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeTransferBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
